### ISSUE TITLE
Result of preprocessors not considerd for exit code

### ISSUE THREAD

**Issue by matthias-dev** [webpro/knip#300]
According to issue #204 the preprocessor api can be used to filter out findings of knip. As far as I understand, the result of the preprocessors are not taken into account for calculating the totalErrorCount which is important for the exit code.
Because you advice to use the preprocessor api for a use case like the one in #204 (filter out findings with complex logic), I think it's a bug that the result of the preprocessors are not taken into account for the exit code.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.34.0. See [Release 2.34.0](https://github.com/webpro/knip/releases/tag/2.34.0) for release notes._

**Comment by matthias-dev** [comment]
Thanks for taking time to work on this issue. But I think it's still not fixed. The CLI command still returns the wrong exit code if issues are filtered by preprocessors. Because firstly the filter method in cli.ts still references the unprocessed report 
`.filter(reportGroup => report[reportGroup] && rules[reportGroup] === 'error')` 
it should be 
`.filter(reportGroup => finalData.report[reportGroup] && rules[reportGroup] === 'error')`.

And secondly the reduce function is using the counters dictionary which I think has to be reevaluated after the preprocessors run?
`.reduce((errorCount: number, reportGroup) => errorCount + counters[reportGroup], 0);`.

**Comment by webpro** [comment]
I've got a temporary solution, need some more time (plus tests!) for this.

For now, the `counters` are sent to the preprocessor, and you can update those so the final result should be based on the updated numbers.
