### ISSUE TITLE
Re-exported enum members incorrectly reported as unused

### ISSUE THREAD

**Issue by renato-bohler** [webpro/knip#647]
Repro: https://stackblitz.com/edit/github-rdchin-5jre6u?file=index.ts&file=myEnum%2Findex.ts&file=myEnum%2FmyEnum.ts

```tsx
// myEnum/myEnum.ts
export enum MyEnum {
  One,
  Two,
  Three,
  Four,
}

// myEnum/index.ts
import { MyEnum } from './myEnum';
export default MyEnum;

// index.ts
import MyEnum from './myEnum';

console.log(MyEnum.One);
console.log(MyEnum.Two);
console.log(MyEnum.Three);
console.log(MyEnum.Four);
```

Running `npm run knip` should report no unused enum members, but it reports all members from `MyEnum` as unused:

![image](https://github.com/webpro/knip/assets/25781956/d8c23a40-2b49-4cd7-b19b-7a707a55fc2a)

If you update the import statement on `index.ts` to `import { MyEnum } from './myEnum/myEnum'`, Knip seems to work properly, only reporting the unused `myEnum/index.ts` file:

![image](https://github.com/webpro/knip/assets/25781956/7aed57cf-cb8d-4065-bc43-303f876507db)

**Comment by webpro** [comment]
Thanks for the report @renato-bohler, should be fixed in next release.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.17.0-canary.0. See [Release 5.17.0-canary.0](https://github.com/webpro/knip/releases/tag/5.17.0-canary.0) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._

**Comment by webpro** [comment]
Would be great if you could try this out on your project:

```
npm install -D knip@canary
```

**Comment by renato-bohler** [comment]
Hmm still doesn't quite work apparently. Here are two scenarios I found:

# Reexporting `default` doesn't report unused members

Knip is **NOT FLAGGING** the enum or its any of its members as unused, when it should:

```tsx
// myEnum/myEnum.ts
export enum MyEnum { One, Two, Three, Four }

// myEnum/index.ts
import { MyEnum } from './myEnum';
export default MyEnum;

// index.ts
import { MyEnum } from './myEnum';
// does nothing with it
```

![image](https://github.com/webpro/knip/assets/25781956/d42a4f34-d433-4f12-8664-dc620ba77e37)

# Reexporting `named` reports used members as unused

Knip is **FLAGGING** the enum members as unused, when they're used:

```tsx
// myEnum/myEnum.ts
export enum MyEnum { One, Two, Three, Four }

// myEnum/index.ts
import { MyEnum } from './myEnum';
export { MyEnum };
// Alternatively: export { MyEnum } from './myEnum';

// index.ts
import { MyEnum } from './myEnum';

console.log(MyEnum.One);
console.log(MyEnum.Two);
console.log(MyEnum.Three);
console.log(MyEnum.Four);
```

![image](https://github.com/webpro/knip/assets/25781956/f93d5972-48da-45dd-a0c0-cdf4933632bd)

**Comment by webpro** [comment]
Thanks @renato-bohler! Very helpful :) Should be better in the latest canary.

**Comment by renato-bohler** [comment]
Nailed it! Seems to work as expected on my project, and I couldn't find any other error scenario.

Thank you for this amazing project!

![image](https://github.com/webpro/knip/assets/25781956/5c9f3a14-86df-4a87-b820-df90fc93b388)

![image](https://github.com/webpro/knip/assets/25781956/f26ef287-e795-4ee0-89e0-8197e8e0fe30)

![image](https://github.com/webpro/knip/assets/25781956/58d08d87-33bd-46f2-8c4f-7a105318d703)
